version: "3.9"

services:
  backend:
    image: 314146333464.dkr.ecr.ap-southeast-1.amazonaws.com/ewallet-backend:${IMAGE_TAG}
    container_name: ewallet-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env