services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped

    network_mode: host
    pid: host

    volumes:
      - /:/host:ro,rslave

    command:
      - "--path.rootfs=/host"